#!/usr/bin/env node

// Initializes file store (../data/data.json) if it doesn't already exist.
var fs = require('fs')
,   path = require('path')
,   dirPath = path.join(__dirname, '../data')
,   filePath = path.join(dirPath, 'data.json')
,   defaultData = [
      { "description": "Sample Todo", "timestamp": 1414528544235},
      { "description": "Sample Todo 2", "timestamp": 1414528754979}
    ]
,   initializeFileStoreLabel = '[initialize-file-store]'

function writeFile (writeFileErr) {
  if (writeFileErr) {
      console.error(initializeFileStoreLabel, writeFileErr)
      process.exit(1)
  }
  console.log(initializeFileStoreLabel, 'successfully created file store at ' + filePath)
}

function makeDataDir (mkdirErr) {
  if (mkdirErr && mkdirErr.code !== 'EEXIST') {
      console.error(initializeFileStoreLabel, mkdirErr)
      process.exit(1)
  }
  fs.writeFile(filePath, JSON.stringify(defaultData), writeFile)        
}

console.log(initializeFileStoreLabel, 'checking whether file store exists yet...')

fs.exists(filePath, function (exists) {
  if (!exists) {
    console.log(initializeFileStoreLabel, 'file store not found. creating at ' + filePath)
    fs.mkdir(dirPath, makeDataDir)
  } else {
    console.log(initializeFileStoreLabel, 'file store found at ' + filePath + '. continuing...')    
  }
})
